//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DynamicDataDisplay.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DynamicDataDisplay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 is in «Auto Fit» mode by default. Using mouse with 的本地化字符串。
        /// </summary>
        internal static string About_1 {
            get {
                return ResourceManager.GetString("About_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse drag 的本地化字符串。
        /// </summary>
        internal static string About_10 {
            get {
                return ResourceManager.GetString("About_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Select an area with current aspect ratio 的本地化字符串。
        /// </summary>
        internal static string About_11 {
            get {
                return ResourceManager.GetString("About_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Select an area to zoom in 的本地化字符串。
        /// </summary>
        internal static string About_12 {
            get {
                return ResourceManager.GetString("About_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Fit to view 的本地化字符串。
        /// </summary>
        internal static string About_13 {
            get {
                return ResourceManager.GetString("About_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Copy screenshot of chart to clipboard 的本地化字符串。
        /// </summary>
        internal static string About_14 {
            get {
                return ResourceManager.GetString("About_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Save screenshot of chart 的本地化字符串。
        /// </summary>
        internal static string About_15 {
            get {
                return ResourceManager.GetString("About_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        internal static string About_2 {
            get {
                return ResourceManager.GetString("About_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pressed down you can manually select an area to display. 的本地化字符串。
        /// </summary>
        internal static string About_3 {
            get {
                return ResourceManager.GetString("About_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse wheel 的本地化字符串。
        /// </summary>
        internal static string About_4 {
            get {
                return ResourceManager.GetString("About_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and 的本地化字符串。
        /// </summary>
        internal static string About_5 {
            get {
                return ResourceManager.GetString("About_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string About_6 {
            get {
                return ResourceManager.GetString("About_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keys  —  Zoom in/Zoom out 的本地化字符串。
        /// </summary>
        internal static string About_7 {
            get {
                return ResourceManager.GetString("About_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse drag 的本地化字符串。
        /// </summary>
        internal static string About_8 {
            get {
                return ResourceManager.GetString("About_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — Pan the display area 的本地化字符串。
        /// </summary>
        internal static string About_9 {
            get {
                return ResourceManager.GetString("About_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About DynamicDataDisplay 的本地化字符串。
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array height should be positive. 的本地化字符串。
        /// </summary>
        internal static string ArrayHeightShouldBePositive {
            get {
                return ResourceManager.GetString("ArrayHeightShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array width should be positive. 的本地化字符串。
        /// </summary>
        internal static string ArrayWidthShouldBePositive {
            get {
                return ResourceManager.GetString("ArrayWidthShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assertion failed. 的本地化字符串。
        /// </summary>
        internal static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assertion failed - search for reasons in code, that is calling method, where this assertion is performed 的本地化字符串。
        /// </summary>
        internal static string AssertionFailedSearch {
            get {
                return ResourceManager.GetString("AssertionFailedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot determine desired type of output image by given file extension. 的本地化字符串。
        /// </summary>
        internal static string CannotDetermineImageTypeByExtension {
            get {
                return ResourceManager.GetString("CannotDetermineImageTypeByExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot get last element of empty list. 的本地化字符串。
        /// </summary>
        internal static string CannotGetLastElement {
            get {
                return ResourceManager.GetString("CannotGetLastElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot modify an empty rect. 的本地化字符串。
        /// </summary>
        internal static string CannotModifyEmptyRect {
            get {
                return ResourceManager.GetString("CannotModifyEmptyRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy screenshot 的本地化字符串。
        /// </summary>
        internal static string ContextMenuCopyScreenshot {
            get {
                return ResourceManager.GetString("ContextMenuCopyScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy screenshot of charts to clipboard 的本地化字符串。
        /// </summary>
        internal static string ContextMenuCopyScreenshotTooltip {
            get {
                return ResourceManager.GetString("ContextMenuCopyScreenshotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit to view 的本地化字符串。
        /// </summary>
        internal static string ContextMenuFitToView {
            get {
                return ResourceManager.GetString("ContextMenuFitToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make visible area fit to display entire contents 的本地化字符串。
        /// </summary>
        internal static string ContextMenuFitToViewTooltip {
            get {
                return ResourceManager.GetString("ContextMenuFitToViewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick help 的本地化字符串。
        /// </summary>
        internal static string ContextMenuQuickHelp {
            get {
                return ResourceManager.GetString("ContextMenuQuickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show brief instructions 的本地化字符串。
        /// </summary>
        internal static string ContextMenuQuickHelpTooltip {
            get {
                return ResourceManager.GetString("ContextMenuQuickHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save screenshot 的本地化字符串。
        /// </summary>
        internal static string ContextMenuSaveScreenshot {
            get {
                return ResourceManager.GetString("ContextMenuSaveScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify name of image file to save screenshot to 的本地化字符串。
        /// </summary>
        internal static string ContextMenuSaveScreenshotTooltip {
            get {
                return ResourceManager.GetString("ContextMenuSaveScreenshotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each transform in transforms should not be null. 的本地化字符串。
        /// </summary>
        internal static string EachTransformShouldNotBeNull {
            get {
                return ResourceManager.GetString("EachTransformShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string ExtensionCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ExtensionCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filepath cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string FilePathCannotbeNullOrEmpty {
            get {
                return ResourceManager.GetString("FilePathCannotbeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal axis can be placed only from bottom or top. 的本地化字符串。
        /// </summary>
        internal static string HorizontalAxisCannotBeVertical {
            get {
                return ResourceManager.GetString("HorizontalAxisCannotBeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis placement is incorrect. 的本地化字符串。
        /// </summary>
        internal static string InvalidAxisPlacement {
            get {
                return ResourceManager.GetString("InvalidAxisPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can hold axis only of {1} type. 的本地化字符串。
        /// </summary>
        internal static string InvalidGenericAxis {
            get {
                return ResourceManager.GetString("InvalidGenericAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value of child&apos;s parent plotter - it should be equal to plotter that child is added to. 的本地化字符串。
        /// </summary>
        internal static string InvalidParentPlotterValue {
            get {
                return ResourceManager.GetString("InvalidParentPlotterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value of child&apos;s parent plotter - it should be equal to plotter that child is being removed from. 的本地化字符串。
        /// </summary>
        internal static string InvalidParentPlotterValueRemoving {
            get {
                return ResourceManager.GetString("InvalidParentPlotterValueRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input data must be more detailized to build isolines. 的本地化字符串。
        /// </summary>
        internal static string IsolinesDataIsUndetailized {
            get {
                return ResourceManager.GetString("IsolinesDataIsUndetailized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data source should be set before building isolines. 的本地化字符串。
        /// </summary>
        internal static string IsolinesDataSourceShouldBeSet {
            get {
                return ResourceManager.GetString("IsolinesDataSourceShouldBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Possible mistake: unsupported case in isoline building. 的本地化字符串。
        /// </summary>
        internal static string IsolinesUnsupportedCase {
            get {
                return ResourceManager.GetString("IsolinesUnsupportedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is not between values in corners. 的本地化字符串。
        /// </summary>
        internal static string IsolinesValueIsOutOfCell {
            get {
                return ResourceManager.GetString("IsolinesValueIsOutOfCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length of colors should be greater or equal to 2. 的本地化字符串。
        /// </summary>
        internal static string PaletteTooFewColors {
            get {
                return ResourceManager.GetString("PaletteTooFewColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter should be positive. 的本地化字符串。
        /// </summary>
        internal static string ParameterShouldBePositive {
            get {
                return ResourceManager.GetString("ParameterShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child&apos;s parent plotter should be equal to null after it was removed from plotter. 的本地化字符串。
        /// </summary>
        internal static string ParentPlotterNotNull {
            get {
                return ResourceManager.GetString("ParentPlotterNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add item to Plotter - first it should be removed from another Plotter. 的本地化字符串。
        /// </summary>
        internal static string PlotterElementAddedToAnotherPlotter {
            get {
                return ResourceManager.GetString("PlotterElementAddedToAnotherPlotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPlotterElement {0} did not removed all its contents from plotter&apos;s visual tree. Change this wrong behaviour in OnPlotterDetaching method of this IPlotterElement. 的本地化字符串。
        /// </summary>
        internal static string PlotterElementDidnotCleanedAfterItself {
            get {
                return ResourceManager.GetString("PlotterElementDidnotCleanedAfterItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text of tick returned by GetStringCore should not be null. 的本地化字符串。
        /// </summary>
        internal static string TextOfTickShouldNotBeNull {
            get {
                return ResourceManager.GetString("TextOfTickShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ticks cannot be generated for this range. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedRangeInAxis {
            get {
                return ResourceManager.GetString("UnsupportedRangeInAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical axis can be placed only from left or right. 的本地化字符串。
        /// </summary>
        internal static string VerticalAxisCannotBeHorizontal {
            get {
                return ResourceManager.GetString("VerticalAxisCannotBeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong state of VisualBindings. 的本地化字符串。
        /// </summary>
        internal static string VisualBindingsWrongState {
            get {
                return ResourceManager.GetString("VisualBindingsWrongState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width and height cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string WidthAndHeightCannotBeNegative {
            get {
                return ResourceManager.GetString("WidthAndHeightCannotBeNegative", resourceCulture);
            }
        }
    }
}
