//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DynamicDataDisplay.Samples.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DynamicDataDisplay.Samples.Strings.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Simple Animation 的本地化字符串。
        /// </summary>
        internal static string AnimationSample {
            get {
                return ResourceManager.GetString("AnimationSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis Coloring 的本地化字符串。
        /// </summary>
        internal static string AxisColoringSample {
            get {
                return ResourceManager.GetString("AxisColoringSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This sample shows how to change axes&apos; colors - looks not stylish, but works :) 的本地化字符串。
        /// </summary>
        internal static string AxisColoringSample_About {
            get {
                return ResourceManager.GetString("AxisColoringSample_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coastline 的本地化字符串。
        /// </summary>
        internal static string Coastline {
            get {
                return ResourceManager.GetString("Coastline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency Exchange Sample 的本地化字符串。
        /// </summary>
        internal static string CurrencyExchangeSample {
            get {
                return ResourceManager.GetString("CurrencyExchangeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden axes and graphics 的本地化字符串。
        /// </summary>
        internal static string HideAxisSample {
            get {
                return ResourceManager.GetString("HideAxisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Histogram 的本地化字符串。
        /// </summary>
        internal static string ImageHistogram {
            get {
                return ResourceManager.GetString("ImageHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isolines 的本地化字符串。
        /// </summary>
        internal static string Isoline {
            get {
                return ResourceManager.GetString("Isoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maps 的本地化字符串。
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mercator Shader Maps 的本地化字符串。
        /// </summary>
        internal static string MercatorShaderMaps {
            get {
                return ResourceManager.GetString("MercatorShaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release 的本地化字符串。
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Samples to release  的本地化字符串。
        /// </summary>
        internal static string ReleaseTooltip {
            get {
                return ResourceManager.GetString("ReleaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long Simulation 的本地化字符串。
        /// </summary>
        internal static string SimulationSample {
            get {
                return ResourceManager.GetString("SimulationSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stock Exchange Sample 的本地化字符串。
        /// </summary>
        internal static string StockExchangeSample {
            get {
                return ResourceManager.GetString("StockExchangeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tooltips on markers 的本地化字符串。
        /// </summary>
        internal static string TooltipSample {
            get {
                return ResourceManager.GetString("TooltipSample", resourceCulture);
            }
        }
    }
}
